services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:
